/-
Copyright (c) 2023 Martin Dvorak. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Martin Dvorak
-/
module

public import Mathlib.Computability.Language
import Mathlib.Data.List.Basic

/-!
# Context-Free Grammars

This file contains the definition of a context-free grammar, which is a grammar that has a single
nonterminal symbol on the left-hand side of each rule.

We restrict nonterminals of a context-free grammar to `Type` because universe polymorphism would be
cumbersome and unnecessary; we can always restrict a context-free grammar to the finitely many
nonterminal symbols that are referred to by its finitely many rules.

## Main definitions
* `ContextFreeGrammar`: A context-free grammar.
* `ContextFreeGrammar.language`: A language generated by a given context-free grammar.

## Main theorems
* `Language.IsContextFree.reverse`: The class of context-free languages is closed under reversal.
* `Language.IsContextFree.union`: The class of context-free languages is closed under union.
* `Language.IsContextFree.mul`: The class of context-free languages is closed under concatenation.
-/

@[expose] public section

open Function

/-- Rule that rewrites a single nonterminal to any string (a list of symbols). -/
@[ext]
structure ContextFreeRule (T N : Type*) where
  /-- Input nonterminal a.k.a. left-hand side. -/
  input : N
  /-- Output string a.k.a. right-hand side. -/
  output : List (Symbol T N)
deriving DecidableEq, Repr

-- See https://github.com/leanprover/lean4/issues/10295
attribute [nolint unusedArguments] instReprContextFreeRule.repr

/-- Context-free grammar that generates words over the alphabet `T` (a type of terminals). -/
structure ContextFreeGrammar (T : Type*) where
  /-- Type of nonterminals. -/
  NT : Type
  /-- Initial nonterminal. -/
  initial : NT
  /-- Rewrite rules. -/
  rules : Finset (ContextFreeRule T NT)

variable {T : Type*}

namespace ContextFreeRule
variable {N : Type*} {r : ContextFreeRule T N} {u v : List (Symbol T N)}

/-- Inductive definition of a single application of a given context-free rule `r` to a string `u`;
`r.Rewrites u v` means that the `r` sends `u` to `v` (there may be multiple such strings `v`). -/
inductive Rewrites (r : ContextFreeRule T N) : List (Symbol T N) → List (Symbol T N) → Prop
  /-- The replacement is at the start of the remaining string. -/
  | head (s : List (Symbol T N)) :
      r.Rewrites (Symbol.nonterminal r.input :: s) (r.output ++ s)
  /-- There is a replacement later in the string. -/
  | cons (x : Symbol T N) {s₁ s₂ : List (Symbol T N)} (hrs : Rewrites r s₁ s₂) :
      r.Rewrites (x :: s₁) (x :: s₂)

lemma Rewrites.exists_parts (hr : r.Rewrites u v) :
    ∃ p q : List (Symbol T N),
      u = p ++ [Symbol.nonterminal r.input] ++ q ∧ v = p ++ r.output ++ q := by
  induction hr with
  | head s =>
    use [], s
    simp
  | cons x _ ih =>
    rcases ih with ⟨p', q', rfl, rfl⟩
    use x :: p', q'
    simp

lemma Rewrites.input_output : r.Rewrites [.nonterminal r.input] r.output := by
  simpa using head []

lemma rewrites_of_exists_parts (r : ContextFreeRule T N) (p q : List (Symbol T N)) :
    r.Rewrites (p ++ [Symbol.nonterminal r.input] ++ q) (p ++ r.output ++ q) := by
  induction p with
  | nil => exact Rewrites.head q
  | cons d l ih => exact Rewrites.cons d ih

/-- Rule `r` rewrites string `u` is to string `v` iff they share both a prefix `p` and postfix `q`
such that the remaining middle part of `u` is the input of `r` and the remaining middle part
of `u` is the output of `r`. -/
theorem rewrites_iff :
    r.Rewrites u v ↔ ∃ p q : List (Symbol T N),
      u = p ++ [Symbol.nonterminal r.input] ++ q ∧ v = p ++ r.output ++ q :=
  ⟨Rewrites.exists_parts, by rintro ⟨p, q, rfl, rfl⟩; apply rewrites_of_exists_parts⟩

lemma Rewrites.nonterminal_input_mem : r.Rewrites u v → .nonterminal r.input ∈ u := by
  simp +contextual [rewrites_iff, List.append_assoc]

/-- Add extra prefix to context-free rewriting. -/
lemma Rewrites.append_left (hvw : r.Rewrites u v) (p : List (Symbol T N)) :
    r.Rewrites (p ++ u) (p ++ v) := by
  rw [rewrites_iff] at *
  rcases hvw with ⟨x, y, hxy⟩
  use p ++ x, y
  simp_all

/-- Add extra postfix to context-free rewriting. -/
lemma Rewrites.append_right (hvw : r.Rewrites u v) (p : List (Symbol T N)) :
    r.Rewrites (u ++ p) (v ++ p) := by
  rw [rewrites_iff] at *
  rcases hvw with ⟨x, y, hxy⟩
  use x, y ++ p
  simp_all

end ContextFreeRule

namespace ContextFreeGrammar

/-- Given a context-free grammar `g` and strings `u` and `v`
`g.Produces u v` means that one step of a context-free transformation by a rule from `g` sends
`u` to `v`. -/
def Produces (g : ContextFreeGrammar T) (u v : List (Symbol T g.NT)) : Prop :=
  ∃ r ∈ g.rules, r.Rewrites u v

/-- Given a context-free grammar `g` and strings `u` and `v`
`g.Derives u v` means that `g` can transform `u` to `v` in some number of rewriting steps. -/
abbrev Derives (g : ContextFreeGrammar T) :
    List (Symbol T g.NT) → List (Symbol T g.NT) → Prop :=
  Relation.ReflTransGen g.Produces

/-- Given a context-free grammar `g` and a string `s`
`g.Generates s` means that `g` can transform its initial nonterminal to `s` in some number of
rewriting steps. -/
def Generates (g : ContextFreeGrammar T) (s : List (Symbol T g.NT)) : Prop :=
  g.Derives [Symbol.nonterminal g.initial] s

/-- The language (set of words) that can be generated by a given context-free grammar `g`. -/
def language (g : ContextFreeGrammar T) : Language T :=
  { w : List T | g.Generates (w.map Symbol.terminal) }

/-- A given word `w` belongs to the language generated by a given context-free grammar `g` iff
`g` can derive the word `w` (wrapped as a string) from the initial nonterminal of `g` in some
number of steps. -/
@[simp]
lemma mem_language_iff (g : ContextFreeGrammar T) (w : List T) :
    w ∈ g.language ↔ g.Derives [Symbol.nonterminal g.initial] (w.map Symbol.terminal) := by
  rfl

variable {g : ContextFreeGrammar T}

@[refl]
lemma Derives.refl (w : List (Symbol T g.NT)) : g.Derives w w :=
  Relation.ReflTransGen.refl

lemma Produces.single {v w : List (Symbol T g.NT)} (hvw : g.Produces v w) : g.Derives v w :=
  Relation.ReflTransGen.single hvw

@[trans]
lemma Derives.trans {u v w : List (Symbol T g.NT)} (huv : g.Derives u v) (hvw : g.Derives v w) :
    g.Derives u w :=
  Relation.ReflTransGen.trans huv hvw

lemma Derives.trans_produces {u v w : List (Symbol T g.NT)}
    (huv : g.Derives u v) (hvw : g.Produces v w) :
    g.Derives u w :=
  huv.trans hvw.single

lemma Produces.trans_derives {u v w : List (Symbol T g.NT)}
    (huv : g.Produces u v) (hvw : g.Derives v w) :
    g.Derives u w :=
  huv.single.trans hvw

lemma Derives.eq_or_head {u w : List (Symbol T g.NT)} (huw : g.Derives u w) :
    u = w ∨ ∃ v : List (Symbol T g.NT), g.Produces u v ∧ g.Derives v w :=
  Relation.ReflTransGen.cases_head huw

lemma derives_iff_eq_or_head {u w : List (Symbol T g.NT)} :
    g.Derives u w ↔ u = w ∨ ∃ v : List (Symbol T g.NT), g.Produces u v ∧ g.Derives v w :=
  Relation.ReflTransGen.cases_head_iff

lemma Derives.eq_or_tail {u w : List (Symbol T g.NT)} (huw : g.Derives u w) :
    w = u ∨ ∃ v : List (Symbol T g.NT), g.Derives u v ∧ g.Produces v w :=
  Relation.ReflTransGen.cases_tail huw

lemma derives_iff_eq_or_tail {u w : List (Symbol T g.NT)} :
    g.Derives u w ↔ w = u ∨ ∃ v : List (Symbol T g.NT), g.Derives u v ∧ g.Produces v w :=
  Relation.ReflTransGen.cases_tail_iff g.Produces u w

/-- Add extra prefix to context-free producing. -/
lemma Produces.append_left {v w : List (Symbol T g.NT)}
    (hvw : g.Produces v w) (p : List (Symbol T g.NT)) :
    g.Produces (p ++ v) (p ++ w) :=
  match hvw with | ⟨r, hrmem, hrvw⟩ => ⟨r, hrmem, hrvw.append_left p⟩

/-- Add extra postfix to context-free producing. -/
lemma Produces.append_right {v w : List (Symbol T g.NT)}
    (hvw : g.Produces v w) (p : List (Symbol T g.NT)) :
    g.Produces (v ++ p) (w ++ p) :=
  match hvw with | ⟨r, hrmem, hrvw⟩ => ⟨r, hrmem, hrvw.append_right p⟩

/-- Add extra prefix to context-free deriving. -/
lemma Derives.append_left {v w : List (Symbol T g.NT)}
    (hvw : g.Derives v w) (p : List (Symbol T g.NT)) :
    g.Derives (p ++ v) (p ++ w) := by
  induction hvw with
  | refl => rfl
  | tail _ last ih => exact ih.trans_produces <| last.append_left p

/-- Add extra postfix to context-free deriving. -/
lemma Derives.append_right {v w : List (Symbol T g.NT)}
    (hvw : g.Derives v w) (p : List (Symbol T g.NT)) :
    g.Derives (v ++ p) (w ++ p) := by
  induction hvw with
  | refl => rfl
  | tail _ last ih => exact ih.trans_produces <| last.append_right p

lemma Produces.exists_nonterminal_input_mem {u v : List (Symbol T g.NT)} (hguv : g.Produces u v) :
    ∃ r ∈ g.rules, .nonterminal r.input ∈ u := by
  obtain ⟨w, l, r⟩ := hguv
  exact ⟨w, l, r.nonterminal_input_mem⟩

lemma derives_nonterminal {t : g.NT} (hgt : ∀ r ∈ g.rules, r.input ≠ t)
    (s : List (Symbol T g.NT)) (hs : s ≠ [.nonterminal t]) :
    ¬g.Derives [.nonterminal t] s := by
  rw [derives_iff_eq_or_head]
  push_neg
  refine ⟨hs.symm, fun _ hx ↦ ?_⟩
  have hxr := hx.exists_nonterminal_input_mem
  simp_rw [List.mem_singleton, Symbol.nonterminal.injEq] at hxr
  tauto

lemma language_eq_zero_of_forall_input_ne_initial (hg : ∀ r ∈ g.rules, r.input ≠ g.initial) :
    g.language = 0 := by ext; simp +contextual [derives_nonterminal, hg]

end ContextFreeGrammar

/-- Context-free languages are defined by context-free grammars. -/
def Language.IsContextFree (L : Language T) : Prop :=
  ∃ g : ContextFreeGrammar T, g.language = L

section closure_reversal

namespace ContextFreeRule
variable {N : Type*} {r : ContextFreeRule T N} {u v : List (Symbol T N)}

/-- Rules for a grammar for a reversed language. -/
def reverse (r : ContextFreeRule T N) : ContextFreeRule T N := ⟨r.input, r.output.reverse⟩

@[simp] lemma reverse_reverse (r : ContextFreeRule T N) : r.reverse.reverse = r := by simp [reverse]

@[simp] lemma reverse_comp_reverse :
    reverse ∘ reverse = (id : ContextFreeRule T N → ContextFreeRule T N) := by ext : 1; simp

lemma reverse_involutive : Involutive (reverse : ContextFreeRule T N → ContextFreeRule T N) :=
  reverse_reverse

lemma reverse_bijective : Bijective (reverse : ContextFreeRule T N → ContextFreeRule T N) :=
  reverse_involutive.bijective

lemma reverse_injective : Injective (reverse : ContextFreeRule T N → ContextFreeRule T N) :=
  reverse_bijective.injective

lemma reverse_surjective : Surjective (reverse : ContextFreeRule T N → ContextFreeRule T N) :=
  reverse_bijective.surjective

protected lemma Rewrites.reverse : ∀ {u v}, r.Rewrites u v → r.reverse.Rewrites u.reverse v.reverse
  | _, _, head s => by simpa using .append_left .input_output _
  | _, _, @cons _ _ _ x u v h => by simpa using h.reverse.append_right _

lemma rewrites_reverse : r.reverse.Rewrites u.reverse v.reverse ↔ r.Rewrites u v :=
  ⟨fun h ↦ by simpa using h.reverse, .reverse⟩

@[simp] lemma rewrites_reverse_comm : r.reverse.Rewrites u v ↔ r.Rewrites u.reverse v.reverse := by
  rw [← rewrites_reverse, reverse_reverse]

end ContextFreeRule

namespace ContextFreeGrammar
variable {g : ContextFreeGrammar T} {u v : List (Symbol T g.NT)} {w : List T}

/-- Grammar for a reversed language. -/
@[simps] def reverse (g : ContextFreeGrammar T) : ContextFreeGrammar T :=
  ⟨g.NT, g.initial, g.rules.map (⟨ContextFreeRule.reverse, ContextFreeRule.reverse_injective⟩)⟩

@[simp] lemma reverse_reverse (g : ContextFreeGrammar T) : g.reverse.reverse = g := by
  simp [reverse, Finset.map_map]

lemma reverse_involutive : Involutive (reverse : ContextFreeGrammar T → ContextFreeGrammar T) :=
  reverse_reverse

lemma reverse_bijective : Bijective (reverse : ContextFreeGrammar T → ContextFreeGrammar T) :=
  reverse_involutive.bijective

lemma reverse_injective : Injective (reverse : ContextFreeGrammar T → ContextFreeGrammar T) :=
  reverse_bijective.injective

lemma reverse_surjective : Surjective (reverse : ContextFreeGrammar T → ContextFreeGrammar T) :=
  reverse_bijective.surjective

lemma produces_reverse : g.reverse.Produces u.reverse v.reverse ↔ g.Produces u v :=
  (Equiv.ofBijective _ ContextFreeRule.reverse_bijective).exists_congr
    (by simp [ContextFreeRule.reverse_involutive.eq_iff])

alias ⟨_, Produces.reverse⟩ := produces_reverse

@[simp] lemma produces_reverse_comm : g.reverse.Produces u v ↔ g.Produces u.reverse v.reverse :=
  (Equiv.ofBijective _ ContextFreeRule.reverse_bijective).exists_congr
    (by simp [ContextFreeRule.reverse_involutive.eq_iff])

protected lemma Derives.reverse (hg : g.Derives u v) : g.reverse.Derives u.reverse v.reverse := by
  induction hg with
  | refl => rfl
  | tail _ orig ih => exact ih.trans_produces orig.reverse

lemma derives_reverse : g.reverse.Derives u.reverse v.reverse ↔ g.Derives u v :=
  ⟨fun h ↦ by convert h.reverse <;> simp, .reverse⟩

@[simp] lemma derives_reverse_comm : g.reverse.Derives u v ↔ g.Derives u.reverse v.reverse := by
  rw [iff_comm, ← derives_reverse, List.reverse_reverse, List.reverse_reverse]

lemma generates_reverse : g.reverse.Generates u.reverse ↔ g.Generates u := by simp [Generates]

alias ⟨_, Generates.reverse⟩ := generates_reverse

@[simp] lemma generates_reverse_comm : g.reverse.Generates u ↔ g.Generates u.reverse := by
  simp [Generates]

@[simp] lemma language_reverse : g.reverse.language = g.language.reverse := by ext; simp

end ContextFreeGrammar

/-- The class of context-free languages is closed under reversal. -/
theorem Language.IsContextFree.reverse (L : Language T) :
    L.IsContextFree → L.reverse.IsContextFree := by rintro ⟨g, rfl⟩; exact ⟨g.reverse, by simp⟩

end closure_reversal

section embed_project

/-! This section contains only auxiliary constructions that will shorten upcoming proofs of
closure properties. When combining several grammars together, we usually want to take a sum type of
their nonterminal types and embed respective nonterminals to this sum type.
We subsequently show that the resulting grammar preserves derivations of those strings that may
contain any terminal symbols but only the proper nonterminal symbols.
The embedding operation must be injective.
The projection operation must be injective on those symbols where it is defined. -/

/-- Mapping `Symbol` when it is a nonterminal. -/
def Symbol.map {N₀ N : Type*} (f : N₀ → N) : Symbol T N₀ → Symbol T N
  | .terminal t => .terminal t
  | .nonterminal n => .nonterminal (f n)

/-- Mapping `Symbol` when it is a nonterminal; may return `none`. -/
def Symbol.filterMap {N₀ N : Type*} (f : N → Option N₀) : Symbol T N → Option (Symbol T N₀)
  | terminal t => some (terminal t)
  | nonterminal n => .map nonterminal (f n)

/-- Map the type of nonterminal symbols of a `ContextFreeRule` . -/
def ContextFreeRule.map {N₀ N : Type*} (r : ContextFreeRule T N₀) (f : N₀ → N) :
    ContextFreeRule T N :=
  ⟨f r.input, r.output.map (.map f)⟩

/-- Map the output symbols of a `ContextFreeRule`, providing the new input nonterminal. -/
def ContextFreeRule.mapSymbol {N₀ N : Type*} (r : ContextFreeRule T N₀)
    (f : Symbol T N₀ → Symbol T N) (input : N) : ContextFreeRule T N :=
  ⟨input, r.output.map f⟩

/-- An embedding from a context-free grammar `g₀` to a context-free grammar `g` is a map on symbols
with a one-sided inverse that respects terminals and nonterminals, and preserves rules. -/
structure ContextFreeGrammar.Embedding (g₀ g : ContextFreeGrammar T) where
  /-- Embedding on symbols. -/
  embed : Symbol T g₀.NT → Symbol T g.NT
  /-- Projection on symbols. -/
  project : Symbol T g.NT → Option (Symbol T g₀.NT)
  /-- The two mappings are essentially inverses. -/
  project_embed (s : Symbol T g₀.NT) : project (embed s) = some s
  /-- Embedding sends nonterminals to nonterminals. -/
  embed_nonterminal (n₀ : g₀.NT) : ∃ n : g.NT, embed (.nonterminal n₀) = .nonterminal n
  /-- Each rule of the smaller grammar has a corresponding rule in the bigger grammar. -/
  embed_mem_rules (r : ContextFreeRule T g₀.NT):
    r ∈ g₀.rules → ∀ n : g.NT,
      embed (.nonterminal r.input) = .nonterminal n →
        (ContextFreeRule.mapSymbol (T := T) r embed n) ∈ g.rules
  /-- Each rule of the bigger grammar whose input nonterminal is recognized by the smaller grammar
  has a corresponding rule in the smaller grammar. -/
  preimage_of_rules (r : ContextFreeRule T g.NT) :
    r ∈ g.rules → ∀ n₀ : g₀.NT,
      embed (.nonterminal n₀) = .nonterminal r.input →
        ∃ r₀ ∈ g₀.rules, r₀.input = n₀ ∧
          ContextFreeRule.mapSymbol (T := T) r₀ embed r.input = r

namespace ContextFreeGrammar.Embedding
variable {g₀ g : ContextFreeGrammar T} {G : g₀.Embedding g}

@[simp] lemma project_embed_apply (s : Symbol T g₀.NT) : G.project (G.embed s) = some s :=
  G.project_embed s

/-- Production by `G.g₀` can be mirrored by production by `G.g`. -/
lemma produces_map {w₁ w₂ : List (Symbol T g₀.NT)}
    (hG : g₀.Produces w₁ w₂) :
    g.Produces (w₁.map G.embed) (w₂.map G.embed) := by
  rcases hG with ⟨r, rin, hr⟩
  rcases hr.exists_parts with ⟨u, v, bef, aft⟩
  rcases G.embed_nonterminal r.input with ⟨n, hn⟩
  refine ⟨ContextFreeRule.mapSymbol (T := T) r G.embed n,
    G.embed_mem_rules r rin n hn, ?_⟩
  rw [ContextFreeRule.rewrites_iff]
  refine ⟨u.map G.embed, v.map G.embed, ?_, ?_⟩
  · simpa [ContextFreeRule.mapSymbol, hn, List.map_append] using
      congr_arg (List.map G.embed) bef
  · simpa only [List.map_append] using congr_arg (List.map G.embed) aft

/-- Derivation by `G.g₀` can be mirrored by derivation by `G.g`. -/
lemma derives_map {w₁ w₂ : List (Symbol T g₀.NT)}
    (hG : g₀.Derives w₁ w₂) :
    g.Derives (w₁.map G.embed) (w₂.map G.embed) := by
  induction hG with
  | refl => rfl
  | tail _ orig ih => exact ih.trans_produces (produces_map orig)

/-- A `Symbol` comes from the embedding. -/
def FromEmbedding (G : g₀.Embedding g) (s : Symbol T g.NT) : Prop :=
  ∃ s₀ : Symbol T g₀.NT, G.embed s₀ = s

/-- A string is from the embedding iff every `Symbol` in it is. -/
def FromEmbeddingString (G : g₀.Embedding g) (s : List (Symbol T g.NT)) : Prop :=
  ∀ ⦃a : Symbol T g.NT⦄, a ∈ s → FromEmbedding G a

lemma fromEmbeddingString_singleton {s : Symbol T g.NT}
    (hs : G.FromEmbedding s) : G.FromEmbeddingString [s] := by
  simpa [FromEmbeddingString] using hs

/-- Production by `G.g` can be mirrored by `G.g₀` production if the first word does not contain any
nonterminals that `G.g₀` lacks. -/
lemma produces_filterMap {w₁ w₂ : List (Symbol T g.NT)}
    (hG : g.Produces w₁ w₂) (hw₁ : G.FromEmbeddingString w₁)
    (hterm : ∀ t : T, ∃ t' : T, G.embed (.terminal t) = .terminal t') :
    g₀.Produces
      (w₁.filterMap G.project)
      (w₂.filterMap G.project) ∧
    G.FromEmbeddingString w₂ := by
  rcases hG with ⟨r, rin, hr⟩
  rcases hr.exists_parts with ⟨u, v, bef, aft⟩
  rw [bef] at hw₁
  have from_embedding_or_terminal_input :
      G.FromEmbedding (Symbol.nonterminal r.input) := by
    apply hw₁
    simp
  rcases from_embedding_or_terminal_input with ⟨s₀, hs₀⟩
  cases s₀ with
  | terminal t =>
    rcases hterm t with ⟨t', ht⟩
    have : (Symbol.terminal t' : Symbol T g.NT) = Symbol.nonterminal r.input := by
      simp [ht] at hs₀
    cases this
  | nonterminal n₀ =>
    have hr_eq : G.embed (.nonterminal n₀) = .nonterminal r.input := hs₀
    rcases G.preimage_of_rules r rin n₀ hr_eq with ⟨r₀, hr₀, hr₀_input, hrr₀⟩
    constructor
    · refine ⟨r₀, hr₀, ?_⟩
      rw [ContextFreeRule.rewrites_iff]
      use u.filterMap G.project, v.filterMap G.project
      have correct_inverse : G.project ∘ G.embed = Option.some := by
        ext x
        simp [project_embed_apply]
      constructor
      · have hproj : G.project (.nonterminal r.input) = some (.nonterminal r₀.input) := by
          have : G.embed (.nonterminal r₀.input) = .nonterminal r.input := by
            simpa [hr₀_input] using hr_eq
          simpa [this] using G.project_embed (.nonterminal r₀.input)
        have middle :
            List.filterMap G.project [Symbol.nonterminal r.input] =
              [Symbol.nonterminal r₀.input] := by
          simp [List.filterMap, hproj]
        have bef' := congr_arg (List.filterMap G.project) bef
        have bef'' :
            List.filterMap G.project w₁ =
              List.filterMap G.project u ++ [Symbol.nonterminal r₀.input] ++
                List.filterMap G.project v := by
          -- expand filterMap over the two appends explicitly
          have bef₁ := bef'
          -- re-associate so we can split twice
          rw [List.append_assoc] at bef₁
          rw [List.filterMap_append] at bef₁
          rw [List.filterMap_append] at bef₁
          simpa [middle] using bef₁
        simpa [ContextFreeRule.mapSymbol, hrr₀] using bef''
      · have aft' := congr_arg (List.filterMap G.project) aft
        have houtput : r.output = r₀.output.map G.embed := by
          simpa [ContextFreeRule.mapSymbol] using (congrArg ContextFreeRule.output hrr₀).symm
        have aft'' :
            List.filterMap G.project w₂ =
              List.filterMap G.project u ++
                List.filterMap G.project (r₀.output.map G.embed) ++
                List.filterMap G.project v := by
          simpa [List.filterMap_append, houtput] using aft'
        simpa [List.filterMap_map, List.filterMap_some, correct_inverse] using aft''
    · rw [aft, ← hrr₀]
      simp only [FromEmbeddingString, List.forall_mem_append] at hw₁ ⊢
      refine ⟨⟨hw₁.left.left, ?_⟩, hw₁.right⟩
      intro a ha
      dsimp only [ContextFreeRule.mapSymbol] at ha
      rw [List.mem_map] at ha
      rcases ha with ⟨s, -, hs⟩
      refine ⟨s, ?_⟩
      simpa using hs

private lemma derives_filterMap_aux {w₁ w₂ : List (Symbol T g.NT)}
    (hG : g.Derives w₁ w₂) (hw₁ : G.FromEmbeddingString w₁)
    (hterm : ∀ t : T, ∃ t' : T, G.embed (.terminal t) = .terminal t') :
    g₀.Derives
      (w₁.filterMap G.project)
      (w₂.filterMap G.project) ∧
    G.FromEmbeddingString w₂ := by
  induction hG with
  | refl => exact ⟨by rfl, hw₁⟩
  | tail _ orig ih =>
    have both := produces_filterMap orig ih.right hterm
    exact ⟨ContextFreeGrammar.Derives.trans_produces ih.left both.left, both.right⟩

/-- Derivation by `G.g` can be mirrored by `G.g₀` derivation if the starting word does not contain
any nonterminals that `G.g₀` lacks. -/
lemma derives_filterMap {w₁ w₂ : List (Symbol T g.NT)}
    (hG : g.Derives w₁ w₂) (hw₁ : G.FromEmbeddingString w₁)
    (hterm : ∀ t : T, ∃ t' : T, G.embed (.terminal t) = .terminal t') :
    g₀.Derives
      (w₁.filterMap G.project)
      (w₂.filterMap G.project) :=
  (derives_filterMap_aux hG hw₁ hterm).left

end ContextFreeGrammar.Embedding
end embed_project

section closure_union

/-- Grammar for a union of two context-free languages. -/
noncomputable def ContextFreeGrammar.union (g₁ g₂ : ContextFreeGrammar T) :
  ContextFreeGrammar T where
  NT := Option (g₁.NT ⊕ g₂.NT)
  initial := none
  rules := by
    let r1 : ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT)) :=
      ⟨none, [Symbol.nonterminal (some (Sum.inl g₁.initial))]⟩
    let r2 : ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT)) :=
      ⟨none, [Symbol.nonterminal (some (Sum.inr g₂.initial))]⟩
    let f₁ : ContextFreeRule T g₁.NT → ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT)) :=
      fun r => r.map (some ∘ Sum.inl)
    let f₂ : ContextFreeRule T g₂.NT → ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT)) :=
      fun r => r.map (some ∘ Sum.inr)
    have h₁ : f₁.Injective := by
      intro ⟨a_in, a_out⟩ ⟨b_in, b_out⟩ hab
      simp only [f₁, ContextFreeRule.map, Function.comp_apply, ContextFreeRule.mk.injEq] at hab ⊢
      obtain ⟨h_in, h_out⟩ := hab
      constructor
      · exact Sum.inl_injective (Option.some_injective _ h_in)
      · rw [List.map_inj_right] at h_out
        · exact h_out
        · intros a b
          intro hs
          cases a <;> cases b <;> simp only [Symbol.map, Symbol.terminal.injEq] at hs ⊢
          repeat' grind
    have h₂ : f₂.Injective := by
      intro ⟨a_in, a_out⟩ ⟨b_in, b_out⟩ hab
      simp only [f₂, ContextFreeRule.map, Function.comp_apply, ContextFreeRule.mk.injEq] at hab ⊢
      obtain ⟨h_in, h_out⟩ := hab
      constructor
      · exact Sum.inr_injective (Option.some_injective _ h_in)
      · have : (Symbol.map (T := T) (N₀ := g₂.NT)
          (N := Option (g₁.NT ⊕ g₂.NT)) (some ∘ Sum.inr)).Injective := by
          intro s1 s2 hs
          cases s1 <;> cases s2 <;> simp only [Symbol.map, Symbol.terminal.injEq] at hs ⊢
          repeat' grind
        exact (List.map_inj_right this).mp h_out
    let mapped1 : Finset (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := g₁.rules.map ⟨f₁, h₁⟩
    let mapped2 : Finset (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := g₂.rules.map ⟨f₂, h₂⟩
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    exact Finset.cons r1 (Finset.cons r2 (mapped1 ∪ mapped2) (by
      intro hr2
      rw [Finset.mem_union] at hr2
      cases hr2 with
      | inl hr2 =>
        rw [Finset.mem_map] at hr2
        obtain ⟨r, _, heq⟩ := hr2
        simp only [f₁, ContextFreeRule.map, r2] at heq
        cases heq
      | inr hr2 =>
        rw [Finset.mem_map] at hr2
        obtain ⟨r, _, heq⟩ := hr2
        simp only [f₂, ContextFreeRule.map, r2] at heq
        cases heq
    )) (by
      intro hr1
      rw [Finset.mem_cons] at hr1
      cases hr1 with
      | inl hr1 =>
        simp [r1, r2] at hr1
      | inr hr1 =>
        rw [Finset.mem_union] at hr1
        cases hr1 with
        | inl hr1 =>
          rw [Finset.mem_map] at hr1
          obtain ⟨r, _, heq⟩ := hr1
          simp only [f₁, ContextFreeRule.map, r1] at heq
          cases heq
        | inr hr1 =>
          rw [Finset.mem_map] at hr1
          obtain ⟨r, _, heq⟩ := hr1
          simp only [f₂, ContextFreeRule.map, r1] at heq
          cases heq
    )

section union_aux

/-- The only interesting declaration in this subsection is the lemma
`ContextFreeGrammar.mem_union_language_iff_mem_or_mem` towards which the whole section builds.
Ignore everything else. -/
private lemma both_empty {u v : List T} {a b : T} (ha : [a] = u ++ [b] ++ v) :
    u = [] ∧ v = [] := by
  cases u <;> cases v <;> simp at ha; trivial

variable {g₁ g₂ : ContextFreeGrammar T}

private def oN₁_of_N : (g₁.union g₂).NT → Option g₁.NT
  | none => none
  | some (Sum.inl n) => some n
  | some (Sum.inr _) => none

private def oN₂_of_N : (g₁.union g₂).NT → Option g₂.NT
  | none => none
  | some (Sum.inl _) => none
  | some (Sum.inr n) => some n

private def g₁g : ContextFreeGrammar.Embedding g₁ (g₁.union g₂) where
  embed := Symbol.map (some ∘ Sum.inl)
  project
    | .terminal t => some (.terminal t)
    | .nonterminal none => none
    | .nonterminal (some (Sum.inl n)) => some (.nonterminal n)
    | .nonterminal (some (Sum.inr _)) => none
  project_embed := by
    intro s
    cases s <;> rfl
  embed_nonterminal := by
    intro n₀
    exact ⟨some (Sum.inl n₀), rfl⟩
  embed_mem_rules := by
    intro r hr n h
    simp only [ContextFreeGrammar.union] at *
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    have hn : n = some (Sum.inl r.input) := by
      simpa [Symbol.map] using (Symbol.nonterminal.inj h.symm)
    subst hn
    apply Finset.mem_cons_of_mem
    apply Finset.mem_cons_of_mem
    apply Finset.mem_union_left
    rw [Finset.mem_map]
    refine ⟨r, hr, rfl⟩
  preimage_of_rules := by
    intro r hr n₀ heq
    simp only [ContextFreeGrammar.union] at hr
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    rcases Finset.mem_cons.mp hr with rfl | hr
    · have : (some (Sum.inl n₀) : Option (g₁.NT ⊕ g₂.NT)) = none := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      cases this
    rcases Finset.mem_cons.mp hr with rfl | hr
    · have : (some (Sum.inl n₀) : Option (g₁.NT ⊕ g₂.NT)) = none := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      cases this
    rcases Finset.mem_union.mp hr with hr | hr
    · rcases Finset.mem_map.mp hr with ⟨r₀, hr₀, hr_eq⟩
      have hr_input : r.input = some (Sum.inl r₀.input) := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have heq' : some (Sum.inl n₀) = r.input := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      have hinput : r₀.input = n₀ := by
        have : (some (Sum.inl n₀) : Option (g₁.NT ⊕ g₂.NT)) =
            some (Sum.inl r₀.input) := by
          simpa [hr_input] using heq'
        exact Sum.inl_injective (Option.some_injective _ this.symm)
      refine ⟨r₀, hr₀, hinput, ?_⟩
      calc
        ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map (some ∘ Sum.inl)) r.input
            = ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map (some ∘ Sum.inl))
                (some (Sum.inl r₀.input)) := by
                  simp [hr_input]
        _ = r₀.map (some ∘ Sum.inl) := by
              rfl
        _ = r := hr_eq
    · exfalso
      rcases Finset.mem_map.mp hr with ⟨r₀, _, hr_eq⟩
      have hr_input : r.input = some (Sum.inr r₀.input) := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have heq' : some (Sum.inl n₀) = r.input := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      have : some (Sum.inl n₀) = some (Sum.inr r₀.input) := by
        simp [hr_input] at heq'
      have : Sum.inl n₀ = Sum.inr r₀.input := Option.some_injective _ this
      cases this

private def g₂g : ContextFreeGrammar.Embedding g₂ (g₁.union g₂) where
  embed := Symbol.map (some ∘ Sum.inr)
  project
    | .terminal t => some (.terminal t)
    | .nonterminal none => none
    | .nonterminal (some (Sum.inl _)) => none
    | .nonterminal (some (Sum.inr n)) => some (.nonterminal n)
  project_embed := by
    intro s
    cases s <;> rfl
  embed_nonterminal := by
    intro n₀
    exact ⟨some (Sum.inr n₀), rfl⟩
  embed_mem_rules := by
    intro r hr n h
    simp only [ContextFreeGrammar.union] at *
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    have hn : n = some (Sum.inr r.input) := by
      simpa [Symbol.map] using (Symbol.nonterminal.inj h.symm)
    subst hn
    apply Finset.mem_cons_of_mem
    apply Finset.mem_cons_of_mem
    apply Finset.mem_union_right
    rw [Finset.mem_map]
    refine ⟨r, hr, rfl⟩
  preimage_of_rules := by
    intro r hr n₀ heq
    simp only [ContextFreeGrammar.union] at hr
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    rcases Finset.mem_cons.mp hr with rfl | hr
    · have : (some (Sum.inr n₀) : Option (g₁.NT ⊕ g₂.NT)) = none := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      cases this
    rcases Finset.mem_cons.mp hr with rfl | hr
    · have : (some (Sum.inr n₀) : Option (g₁.NT ⊕ g₂.NT)) = none := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      cases this
    rcases Finset.mem_union.mp hr with hr | hr
    · exfalso
      rcases Finset.mem_map.mp hr with ⟨r₀, _, hr_eq⟩
      have hr_input : r.input = some (Sum.inl r₀.input) := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have heq' : some (Sum.inr n₀) = r.input := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      have : some (Sum.inr n₀) = some (Sum.inl r₀.input) := by
        simp [hr_input] at heq'
      have : Sum.inr n₀ = Sum.inl r₀.input := Option.some_injective _ this
      cases this
    · rcases Finset.mem_map.mp hr with ⟨r₀, hr₀, hr_eq⟩
      have hr_input : r.input = some (Sum.inr r₀.input) := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have heq' : some (Sum.inr n₀) = r.input := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      have hinput : r₀.input = n₀ := by
        have : (some (Sum.inr n₀) : Option (g₁.NT ⊕ g₂.NT)) =
            some (Sum.inr r₀.input) := by
          simpa [hr_input] using heq'
        exact Sum.inr_injective (Option.some_injective _ this.symm)
      refine ⟨r₀, hr₀, hinput, ?_⟩
      calc
        ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map (some ∘ Sum.inr)) r.input
            = ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map (some ∘ Sum.inr))
                (some (Sum.inr r₀.input)) := by
                simp [hr_input]
        _ = r₀.map (some ∘ Sum.inr) := by
              rfl
        _ = r := hr_eq

private lemma union_derives_left_initial :
    (g₁.union g₂).Derives [Symbol.nonterminal (none : (g₁.union g₂).NT)]
      [Symbol.nonterminal (some (Sum.inl g₁.initial) : (g₁.union g₂).NT)] := by
  refine ContextFreeGrammar.Produces.single
    ⟨⟨none, [Symbol.nonterminal (some (Sum.inl g₁.initial))]⟩, ?_, ?_⟩
  · simp only [ContextFreeGrammar.union]
    apply Finset.mem_cons_self
  · rw [ContextFreeRule.rewrites_iff]
    use [], []
    simp

private lemma union_derives_right_initial :
    (g₁.union g₂).Derives [Symbol.nonterminal (none : (g₁.union g₂).NT)]
      [Symbol.nonterminal (some (Sum.inr g₂.initial) : (g₁.union g₂).NT)] := by
  refine ContextFreeGrammar.Produces.single
    ⟨⟨none, [Symbol.nonterminal (some (Sum.inr g₂.initial))]⟩, ?_, ?_⟩
  · simp only [ContextFreeGrammar.union]
    apply Finset.mem_cons_of_mem
    apply Finset.mem_cons_self
  · rw [ContextFreeRule.rewrites_iff]
    use [], []
    simp

variable {w : List T}

private lemma in_union_of_in_left (hw : w ∈ g₁.language) : w ∈ (g₁.union g₂).language := by
  refine union_derives_left_initial.trans ?_
  have h :
      (w.map (Symbol.terminal (N := g₁.NT))).map g₁g.embed =
        w.map (Symbol.terminal (N := (g₁.union g₂).NT)) := by
    cases w with
    | nil => rfl
    | cons t w => simp [g₁g, Symbol.map]
  rw [← h]
  exact g₁g.derives_map hw

private lemma in_union_of_in_right (hw : w ∈ g₂.language) : w ∈ (g₁.union g₂).language := by
  refine union_derives_right_initial.trans ?_
  have h :
      (w.map (Symbol.terminal (N := g₂.NT))).map g₂g.embed =
        w.map (Symbol.terminal (N := (g₁.union g₂).NT)) := by
    cases w with
    | nil => rfl
    | cons t w => simp [g₂g, Symbol.map]
  rw [← h]
  exact g₂g.derives_map hw

private lemma List.filterMap_project_terminal {N₀ N : Type*}
    (project : Symbol T N → Option (Symbol T N₀))
    (hproj : ∀ t : T, project (.terminal t) = some (.terminal t))
    (w : List T) :
    List.filterMap project (w.map Symbol.terminal) = w.map Symbol.terminal := by
  induction w with
  | nil => rfl
  | cons t _ ih => simp [hproj, ih]

private lemma in_left_of_in_union (hw : (g₁.union g₂).Derives
      [Symbol.nonterminal (some (Sum.inl g₁.initial) : (g₁.union g₂).NT)]
      (List.map Symbol.terminal w)) :
    w ∈ g₁.language := by
  have hterm :
      List.filterMap g₁g.project (List.map (Symbol.terminal (N := (g₁.union g₂).NT)) w) =
        List.map (Symbol.terminal (N := g₁.NT)) w :=
    List.filterMap_project_terminal g₁g.project (by intro t; simp [g₁g]) w
  have h := g₁g.derives_filterMap hw
    (by
      intro a ha
      simp only [List.mem_cons, List.not_mem_nil, or_false] at ha
      rw [ha]
      exact ⟨Symbol.nonterminal g₁.initial, by simp [g₁g, Symbol.map]⟩)
    (by
      intro t
      exact ⟨t, by simp [g₁g, Symbol.map]⟩)
  have h' : g₁.Derives
      (List.filterMap g₁g.project
        [Symbol.nonterminal (some (Sum.inl g₁.initial) : (g₁.union g₂).NT)])
      (List.map Symbol.terminal w) := by
    simpa [hterm] using h
  simpa [g₁g] using h'

private lemma in_right_of_in_union (hw : (g₁.union g₂).Derives
      [Symbol.nonterminal (some (Sum.inr g₂.initial) : (g₁.union g₂).NT)]
      (List.map Symbol.terminal w)) :
    w ∈ g₂.language := by
  have hterm :
      List.filterMap g₂g.project (List.map (Symbol.terminal (N := (g₁.union g₂).NT)) w) =
        List.map (Symbol.terminal (N := g₂.NT)) w :=
    List.filterMap_project_terminal g₂g.project (by intro t; simp [g₂g]) w
  have h := g₂g.derives_filterMap hw
    (by
      intro a ha
      simp only [List.mem_cons, List.not_mem_nil, or_false] at ha
      rw [ha]
      exact ⟨Symbol.nonterminal g₂.initial, by simp [g₂g, Symbol.map]⟩)
    (by
      intro t
      exact ⟨t, by simp [g₂g, Symbol.map]⟩)
  have h' : g₂.Derives
      (List.filterMap g₂g.project
        [Symbol.nonterminal (some (Sum.inr g₂.initial) : (g₁.union g₂).NT)])
      (List.map Symbol.terminal w) := by
    simpa [hterm] using h
  simpa [g₂g] using h'

private lemma map_inl_injective : ((ContextFreeRule.map · (Option.some ∘ Sum.inl)) :
    ContextFreeRule T g₁.NT → ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))).Injective := by
  intro ⟨a_in, a_out⟩ ⟨b_in, b_out⟩ hab
  simp only [ContextFreeRule.map, comp_apply, ContextFreeRule.mk.injEq, Option.some.injEq,
    Sum.inl.injEq] at hab
  simp only [hab.left, ContextFreeRule.mk.injEq, true_and]
  rw [List.map_inj_right] at hab
  · simp [hab]
  · intros a b
    intro hs
    cases a <;> cases b <;> simp only [Symbol.map, Symbol.terminal.injEq] at hs ⊢
    repeat' grind

private lemma map_inr_injective : ((ContextFreeRule.map · (Option.some ∘ Sum.inr)) :
    ContextFreeRule T g₂.NT → ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))).Injective := by
  intro ⟨a_in, a_out⟩ ⟨b_in, b_out⟩ hab
  simp only [ContextFreeRule.map, comp_apply, ContextFreeRule.mk.injEq, Option.some.injEq,
    Sum.inr.injEq] at hab
  simp only [hab.left, ContextFreeRule.mk.injEq, true_and]
  rw [List.map_inj_right] at hab
  · simp [hab]
  · intros a b
    intro hs
    cases a <;> cases b <;> simp only [Symbol.map, Symbol.terminal.injEq] at hs ⊢
    repeat' grind

private lemma impossible_rule {r : ContextFreeRule T (g₁.union g₂).NT}
    (hg : [Symbol.nonterminal (g₁.union g₂).initial] =
      ([] : List (Symbol T (g₁.union g₂).NT)) ++ [Symbol.nonterminal r.input] ++
      ([] : List (Symbol T (g₁.union g₂).NT)))
    (hr : letI : DecidableEq T := Classical.decEq T;
          letI : DecidableEq g₁.NT := Classical.decEq g₁.NT;
          letI : DecidableEq g₂.NT := Classical.decEq g₂.NT;
          letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _;
          letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _;
          r ∈ (g₁.rules.map ⟨(ContextFreeRule.map · (Option.some ∘ Sum.inl)), map_inl_injective⟩ ∪
               g₂.rules.map ⟨(ContextFreeRule.map · (Option.some ∘ Sum.inr)), map_inr_injective⟩)) :
    False := by
  letI : DecidableEq T := Classical.decEq T
  letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
  letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
  letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
  letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
  have rule_root : none = r.input := Symbol.nonterminal.inj (List.head_eq_of_cons_eq hg)
  rw [Finset.mem_union] at hr
  cases hr with
  | inl hr' =>
    rw [Finset.mem_map] at hr'
    rcases hr' with ⟨r₀, _, rfl⟩
    simp [ContextFreeRule.map] at rule_root
  | inr hr' =>
    rw [Finset.mem_map] at hr'
    rcases hr' with ⟨r₀, _, rfl⟩
    simp [ContextFreeRule.map] at rule_root

private lemma in_language_of_in_union (hw : w ∈ (g₁.union g₂).language) :
    w ∈ g₁.language ∨ w ∈ g₂.language := by
  cases hw.eq_or_head with
  | inl impossible =>
    exfalso
    cases w
    · cases impossible
    · cases impossible
  | inr hv =>
    rcases hv with ⟨_, ⟨r, hr, hrr⟩, hg⟩
    rcases hrr.exists_parts with ⟨u, v, huv, rfl⟩
    rcases both_empty huv with ⟨rfl, rfl⟩
    simp only [ContextFreeGrammar.union] at hr
    rcases Finset.mem_cons.mp hr with rfl | hr
    · left
      exact in_left_of_in_union hg
    rcases Finset.mem_cons.mp hr with rfl | hr
    · right
      exact in_right_of_in_union hg
    exfalso
    exact impossible_rule huv hr

lemma ContextFreeGrammar.mem_union_language_iff_mem_or_mem :
    w ∈ (g₁.union g₂).language ↔ w ∈ g₁.language ∨ w ∈ g₂.language :=
  ⟨in_language_of_in_union, fun hw => hw.elim in_union_of_in_left in_union_of_in_right⟩

end union_aux

/-- The class of context-free languages is closed under union. -/
theorem Language.IsContextFree.union {L₁ L₂ : Language T} :
    L₁.IsContextFree → L₂.IsContextFree → (L₁ + L₂).IsContextFree := by
  rintro ⟨g₁, rfl⟩ ⟨g₂, rfl⟩
  exact ⟨g₁.union g₂, Set.ext (fun _ =>
    ContextFreeGrammar.mem_union_language_iff_mem_or_mem)⟩

end closure_union

section closure_concatenation

/-- Grammar for concatenation of two context-free languages. -/
noncomputable def ContextFreeGrammar.concat (g₁ g₂ : ContextFreeGrammar T) :
  ContextFreeGrammar T where
  NT := Option (g₁.NT ⊕ g₂.NT)
  initial := none
  rules := by
    let r : ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT)) :=
      ⟨none, [Symbol.nonterminal (some (Sum.inl g₁.initial)),
              Symbol.nonterminal (some (Sum.inr g₂.initial))]⟩
    let f₁ : ContextFreeRule T g₁.NT → ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT)) :=
      fun r => r.map (some ∘ Sum.inl)
    let f₂ : ContextFreeRule T g₂.NT → ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT)) :=
      fun r => r.map (some ∘ Sum.inr)
    have h₁ : f₁.Injective := by
      intro ⟨a_in, a_out⟩ ⟨b_in, b_out⟩ hab
      simp only [f₁, ContextFreeRule.map, Function.comp_apply, ContextFreeRule.mk.injEq] at hab ⊢
      obtain ⟨h_in, h_out⟩ := hab
      constructor
      · exact Sum.inl_injective (Option.some_injective _ h_in)
      · rw [List.map_inj_right] at h_out
        · exact h_out
        · intros a b
          intro hs
          cases a <;> cases b <;> simp only [Symbol.map, Symbol.terminal.injEq] at hs ⊢
          repeat' grind
    have h₂ : f₂.Injective := by
      intro ⟨a_in, a_out⟩ ⟨b_in, b_out⟩ hab
      simp only [f₂, ContextFreeRule.map, Function.comp_apply, ContextFreeRule.mk.injEq] at hab ⊢
      obtain ⟨h_in, h_out⟩ := hab
      constructor
      · exact Sum.inr_injective (Option.some_injective _ h_in)
      · have : (Symbol.map (T := T) (N₀ := g₂.NT)
          (N := Option (g₁.NT ⊕ g₂.NT)) (some ∘ Sum.inr)).Injective := by
          intro s1 s2 hs
          cases s1 <;> cases s2 <;> simp only [Symbol.map, Symbol.terminal.injEq] at hs ⊢
          repeat' grind
        exact (List.map_inj_right this).mp h_out
    let mapped1 : Finset (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := g₁.rules.map ⟨f₁, h₁⟩
    let mapped2 : Finset (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := g₂.rules.map ⟨f₂, h₂⟩
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    exact Finset.cons r (mapped1 ∪ mapped2) (by
      intro hr
      rw [Finset.mem_union] at hr
      cases hr with
      | inl hr =>
        rw [Finset.mem_map] at hr
        obtain ⟨r', _, heq⟩ := hr
        simp only [f₁, ContextFreeRule.map, r] at heq
        cases heq
      | inr hr =>
        rw [Finset.mem_map] at hr
        obtain ⟨r', _, heq⟩ := hr
        simp only [f₂, ContextFreeRule.map, r] at heq
        cases heq
    )

section concat_aux

variable {g₁ g₂ : ContextFreeGrammar T}

private def oN₁_of_N_concat : (g₁.concat g₂).NT → Option g₁.NT
  | none => none
  | some (Sum.inl n) => some n
  | some (Sum.inr _) => none

private def oN₂_of_N_concat : (g₁.concat g₂).NT → Option g₂.NT
  | none => none
  | some (Sum.inl _) => none
  | some (Sum.inr n) => some n

private def g₁g_concat : ContextFreeGrammar.Embedding g₁ (g₁.concat g₂) where
  embed := Symbol.map (some ∘ Sum.inl)
  project
    | .terminal t => some (.terminal t)
    | .nonterminal none => none
    | .nonterminal (some (Sum.inl n)) => some (.nonterminal n)
    | .nonterminal (some (Sum.inr _)) => none
  project_embed := by
    intro s
    cases s <;> rfl
  embed_nonterminal := by
    intro n₀
    exact ⟨some (Sum.inl n₀), rfl⟩
  embed_mem_rules := by
    intro r hr n h
    simp only [ContextFreeGrammar.concat] at *
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    have hn : n = some (Sum.inl r.input) := by
      simpa [Symbol.map] using (Symbol.nonterminal.inj h.symm)
    subst hn
    apply Finset.mem_cons_of_mem
    apply Finset.mem_union_left
    rw [Finset.mem_map]
    refine ⟨r, hr, rfl⟩
  preimage_of_rules := by
    intro r hr n₀ heq
    simp only [ContextFreeGrammar.concat] at hr
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    rcases Finset.mem_cons.mp hr with rfl | hr
    · have : (some (Sum.inl n₀) : Option (g₁.NT ⊕ g₂.NT)) = none := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      cases this
    rcases Finset.mem_union.mp hr with hr | hr
    · rcases Finset.mem_map.mp hr with ⟨r₀, hr₀, hr_eq⟩
      have hr_input : r.input = some (Sum.inl r₀.input) := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have heq' : some (Sum.inl n₀) = r.input := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      have hinput : r₀.input = n₀ := by
        have : (some (Sum.inl n₀) : Option (g₁.NT ⊕ g₂.NT)) =
            some (Sum.inl r₀.input) := by
          simpa [hr_input] using heq'
        exact Sum.inl_injective (Option.some_injective _ this.symm)
      refine ⟨r₀, hr₀, hinput, ?_⟩
      calc
        ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map (some ∘ Sum.inl)) r.input
            = ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map (some ∘ Sum.inl))
                (some (Sum.inl r₀.input)) := by
                simp [hr_input]
        _ = r₀.map (some ∘ Sum.inl) := by
              rfl
        _ = r := hr_eq
    · exfalso
      rcases Finset.mem_map.mp hr with ⟨r₀, _, hr_eq⟩
      have hr_input : r.input = some (Sum.inr r₀.input) := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have heq' : some (Sum.inl n₀) = r.input := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      have : some (Sum.inl n₀) = some (Sum.inr r₀.input) := by
        simp [hr_input] at heq'
      have : Sum.inl n₀ = Sum.inr r₀.input := Option.some_injective _ this
      cases this

private def g₂g_concat : ContextFreeGrammar.Embedding g₂ (g₁.concat g₂) where
  embed := Symbol.map (some ∘ Sum.inr)
  project
    | .terminal t => some (.terminal t)
    | .nonterminal none => none
    | .nonterminal (some (Sum.inl _)) => none
    | .nonterminal (some (Sum.inr n)) => some (.nonterminal n)
  project_embed := by
    intro s
    cases s <;> rfl
  embed_nonterminal := by
    intro n₀
    exact ⟨some (Sum.inr n₀), rfl⟩
  embed_mem_rules := by
    intro r hr n h
    simp only [ContextFreeGrammar.concat] at *
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    have hn : n = some (Sum.inr r.input) := by
      simpa [Symbol.map] using (Symbol.nonterminal.inj h.symm)
    subst hn
    apply Finset.mem_cons_of_mem
    apply Finset.mem_union_right
    rw [Finset.mem_map]
    refine ⟨r, hr, rfl⟩
  preimage_of_rules := by
    intro r hr n₀ heq
    simp only [ContextFreeGrammar.concat] at hr
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
    rcases Finset.mem_cons.mp hr with rfl | hr
    · have : (some (Sum.inr n₀) : Option (g₁.NT ⊕ g₂.NT)) = none := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      cases this
    rcases Finset.mem_union.mp hr with hr | hr
    · exfalso
      rcases Finset.mem_map.mp hr with ⟨r₀, _, hr_eq⟩
      have hr_input : r.input = some (Sum.inl r₀.input) := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have heq' : some (Sum.inr n₀) = r.input := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      have : some (Sum.inr n₀) = some (Sum.inl r₀.input) := by
        simp [hr_input] at heq'
      have : Sum.inr n₀ = Sum.inl r₀.input := Option.some_injective _ this
      cases this
    · rcases Finset.mem_map.mp hr with ⟨r₀, hr₀, hr_eq⟩
      have hr_input : r.input = some (Sum.inr r₀.input) := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have heq' : some (Sum.inr n₀) = r.input := by
        simpa [Symbol.map] using (Symbol.nonterminal.inj heq)
      have hinput : r₀.input = n₀ := by
        have : (some (Sum.inr n₀) : Option (g₁.NT ⊕ g₂.NT)) =
            some (Sum.inr r₀.input) := by
          simpa [hr_input] using heq'
        exact Sum.inr_injective (Option.some_injective _ this.symm)
      refine ⟨r₀, hr₀, hinput, ?_⟩
      calc
        ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map (some ∘ Sum.inr)) r.input
            = ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map (some ∘ Sum.inr))
                (some (Sum.inr r₀.input)) := by
                simp [hr_input]
        _ = r₀.map (some ∘ Sum.inr) := by
              rfl
        _ = r := hr_eq

private lemma concat_derives_both_initials :
    (g₁.concat g₂).Derives [Symbol.nonterminal (none : (g₁.concat g₂).NT)]
      [Symbol.nonterminal (some (Sum.inl g₁.initial)),
       Symbol.nonterminal (some (Sum.inr g₂.initial))] := by
  refine ContextFreeGrammar.Produces.single
    ⟨⟨none, [Symbol.nonterminal (some (Sum.inl g₁.initial)),
             Symbol.nonterminal (some (Sum.inr g₂.initial))]⟩, ?_, ?_⟩
  · simp only [ContextFreeGrammar.concat]
    apply Finset.mem_cons_self
  · rw [ContextFreeRule.rewrites_iff]
    use [], []
    simp

variable {w : List T}
private lemma head_tail_split {g : ContextFreeGrammar T}
    (x : List (Symbol T g.NT)) (s : Symbol T g.NT) (ss : List (Symbol T g.NT))
    (hyp : g.Derives (s :: ss) x) :
    ∃ u v : List (Symbol T g.NT), g.Derives [s] u ∧ g.Derives ss v ∧ u ++ v = x := by
  induction hyp with
  | refl => exact ⟨[s], ss, by rfl, by rfl, rfl⟩
  | tail rel trans ih =>
    rcases ih with ⟨u, v, hu, hv, huv⟩
    rcases trans with ⟨rule, rule_in, hrule⟩
    rcases hrule.exists_parts with ⟨c, d, bef, aft⟩
    have bef' : c ++ [Symbol.nonterminal rule.input] ++ d = u ++ v := by rw [← bef, huv]
    by_cases left_side : c.length < u.length
    · -- Transformation happens within u
      have h_c_prefix : c = u.take c.length := by
        have : (u ++ v).take c.length = c := by
          calc (u ++ v).take c.length
            _ = (c ++ [Symbol.nonterminal rule.input] ++ d).take c.length := by rw [← bef']
            _ = c := by simp
        rw [this.symm]
        simp [List.take_append_of_le_length (Nat.le_of_lt left_side)]
      set rest := u.drop c.length
      have hu_split : u = c ++ rest := by rw [h_c_prefix]; exact (List.take_append_drop _ _).symm
      have h_rest_eq : [Symbol.nonterminal rule.input] ++ d = rest ++ v := by
        have : c ++ [Symbol.nonterminal rule.input] ++ d = c ++ rest ++ v := by
          rw [← hu_split]
          exact bef'
        have h' : c ++ ([Symbol.nonterminal rule.input] ++ d) = c ++ (rest ++ v) := by
          simpa [List.append_assoc]
        exact List.append_cancel_left h'
      have hrest_nonempty : rest ≠ [] := by
        intro h
        rw [h] at h_rest_eq; simp at h_rest_eq
        have : u.length = c.length := by rw [hu_split, h]; simp
        omega
      obtain ⟨hd_rest, tl_rest, h_rest_cons⟩ := List.exists_cons_of_ne_nil hrest_nonempty
      have h_hd : hd_rest = Symbol.nonterminal rule.input := by
        have : [Symbol.nonterminal rule.input] ++ d = hd_rest :: (tl_rest ++ v) := by
          grind
        exact List.head_eq_of_cons_eq this.symm
      use c ++ rule.output ++ tl_rest, v
      refine ⟨?_, hv, ?_⟩
      · have : u = c ++ [Symbol.nonterminal rule.input] ++ tl_rest := by
          simp [hu_split, h_rest_cons, h_hd]
        rw [this] at hu
        exact hu.trans_produces
          ⟨rule, rule_in, by simp only [List.append_assoc, List.cons_append, List.nil_append,
            ContextFreeRule.rewrites_iff]; use c, tl_rest⟩
      · grind
    · -- Transformation happens within v
      have h_u_le_c : u.length ≤ c.length := Nat.ge_of_not_lt left_side
      have h_u_prefix : u = c.take u.length := by
        have : (u ++ v).take u.length = u := List.take_left
        calc u = (u ++ v).take u.length := this.symm
          _ = (c ++ [Symbol.nonterminal rule.input] ++ d).take u.length := by rw [← bef']
          _ = c.take u.length := by simp [List.take_append_of_le_length h_u_le_c]
      set c' := c.drop u.length
      have hc_split : c = u ++ c' := by rw [h_u_prefix]; exact (List.take_append_drop _ _).symm
      have hv_eq : v = c' ++ [Symbol.nonterminal rule.input] ++ d := by
        have : u ++ c' ++ [Symbol.nonterminal rule.input] ++ d = u ++ v := by
          rw [← hc_split]; exact bef'
        simp only [List.append_assoc, List.cons_append, List.nil_append,
          List.append_cancel_left_eq] at this
        simp only [List.append_assoc, List.cons_append, List.nil_append, this]
      use u, c' ++ rule.output ++ d
      refine ⟨hu, ?_, ?_⟩
      · rw [hv_eq] at hv
        exact hv.trans_produces ⟨rule, rule_in, by simp only [List.append_assoc, List.cons_append,
          List.nil_append, ContextFreeRule.rewrites_iff]; use c', d⟩
      · grind

/-- Corollary: derivation from two symbols can be split. -/
private lemma concatenation_split {g : ContextFreeGrammar T}
    (x : List (Symbol T g.NT)) (s t : Symbol T g.NT) (hyp : g.Derives [s, t] x) :
    ∃ u v : List (Symbol T g.NT), g.Derives [s] u ∧ g.Derives [t] v ∧ u ++ v = x :=
  head_tail_split x s [t] hyp


private lemma in_concat_of_in_left_and_right {w₁ w₂ : List T}
    (hw₁ : w₁ ∈ g₁.language) (hw₂ : w₂ ∈ g₂.language) :
    w₁ ++ w₂ ∈ (g₁.concat g₂).language := by
  refine concat_derives_both_initials.trans ?_
  rw [List.map_append]
  have h1 :
      (w₁.map (Symbol.terminal (N := g₁.NT))).map g₁g_concat.embed =
        w₁.map (Symbol.terminal (N := (g₁.concat g₂).NT)) := by
    cases w₁ with
    | nil => rfl
    | cons t w => simp [g₁g_concat, Symbol.map]
  have h2 :
      (w₂.map (Symbol.terminal (N := g₂.NT))).map g₂g_concat.embed =
        w₂.map (Symbol.terminal (N := (g₁.concat g₂).NT)) := by
    cases w₂ with
    | nil => rfl
    | cons t w => simp [g₂g_concat, Symbol.map]
  rw [← h1, ← h2]
  exact (g₁g_concat.derives_map hw₁).append_right _
    |>.trans ((g₂g_concat.derives_map hw₂).append_left _)

private lemma filterMap_terminals_eq {N N' : Type*} (project : Symbol T N → Option (Symbol T N'))
    (hproj : ∀ t : T, project (.terminal t) = some (.terminal t)) (w : List T) :
    (w.map (Symbol.terminal (N := N))).filterMap project =
      w.map (Symbol.terminal (N := N')) := by
  induction w with
  | nil => rfl
  | cons t w ih => simp [hproj, ih]

/-- Extract terminals from a symbol list. -/
private def extractTerminals {N : Type*} : List (Symbol T N) → List T
  | [] => []
  | Symbol.terminal t :: rest => t :: extractTerminals rest
  | Symbol.nonterminal _ :: rest => extractTerminals rest

private lemma extractTerminals_map_terminal {N : Type*} (w : List T) :
    extractTerminals (w.map (Symbol.terminal (N := N))) = w := by
  induction w with
  | nil => rfl
  | cons t w ih => simp [extractTerminals, ih]

private lemma extractTerminals_append {N : Type*} (s₁ s₂ : List (Symbol T N)) :
    extractTerminals (s₁ ++ s₂) = extractTerminals s₁ ++ extractTerminals s₂ := by
  induction s₁ with
  | nil => rfl
  | cons head tail ih =>
    cases head with
    | terminal t => simp [extractTerminals, ih]
    | nonterminal n => simp [extractTerminals, ih]

private lemma extractTerminals_filterMap_terminals {N₁ N₂ : Type*}
    (project : Symbol T N₂ → Option (Symbol T N₁))
    (hproj : ∀ t : T, project (.terminal t) = some (.terminal t))
    (s : List (Symbol T N₂)) (hs : ∀ x ∈ s, ∃ t : T, x = Symbol.terminal t) :
    extractTerminals s = extractTerminals (s.filterMap project) := by
  induction s with
  | nil => rfl
  | cons head tail ih =>
    have h_head := hs head (by simp)
    obtain ⟨t, rfl⟩ := h_head
    have h_tail : ∀ x ∈ tail, ∃ t : T, x = Symbol.terminal t := fun x hx => hs x (by simp [hx])
    simp [extractTerminals, List.filterMap, hproj, ih h_tail]

private lemma map_terminal_extractTerminals {N : Type*} (s : List (Symbol T N))
    (hs : ∀ x ∈ s, ∃ t : T, x = Symbol.terminal t) :
    (extractTerminals s).map Symbol.terminal = s := by
  induction s with
  | nil => rfl
  | cons head tail ih =>
    have h_head := hs head (by simp)
    obtain ⟨t, rfl⟩ := h_head
    have h_tail : ∀ x ∈ tail, ∃ t : T, x = Symbol.terminal t := fun x hx => hs x (by simp [hx])
    simp [extractTerminals, ih h_tail]

private lemma filterMap_only_terminals {N₁ N₂ : Type*}
    (project : Symbol T N₂ → Option (Symbol T N₁))
    (hproj : ∀ t : T, project (.terminal t) = some (.terminal t))
    (s : List (Symbol T N₂)) (hs : ∀ x ∈ s, ∃ t : T, x = Symbol.terminal t) :
    ∀ x ∈ s.filterMap project, ∃ t : T, x = Symbol.terminal t := by
  intro x hx
  simp only [List.mem_filterMap] at hx
  obtain ⟨y, hy_mem, hy_eq⟩ := hx
  obtain ⟨t, rfl⟩ := hs y hy_mem
  simp [hproj] at hy_eq
  exact ⟨t, hy_eq.symm⟩

lemma ContextFreeGrammar.mem_concat_language_iff_mem_mul :
    w ∈ (g₁.concat g₂).language ↔ ∃ w₁ ∈ g₁.language, ∃ w₂ ∈ g₂.language, w = w₁ ++ w₂ := by
  constructor
  · intro hw
    cases hw.eq_or_head with
    | inl impossible =>
      exfalso
      cases w
      · cases impossible
      · cases impossible
    | inr hv =>
      rcases hv with ⟨v, ⟨r, hr, hrr⟩, hg⟩
      rcases hrr.exists_parts with ⟨u', v', huv, rfl⟩
      have both_empty : u' = [] ∧ v' = [] := by
        cases u' <;> cases v' <;> simp at huv; trivial
      rcases both_empty with ⟨rfl, rfl⟩
      simp only [ContextFreeGrammar.concat, List.nil_append, List.append_nil] at hr huv hg
      rcases Finset.mem_cons.mp hr with rfl | hr
      · -- The case where r is the concatenation rule
        -- Use splitting to get two separate derivations
        obtain ⟨u'', v'', hu'', hv'', huv''⟩ := concatenation_split _ _ _ hg
        -- Extract words from the combined grammar back to original grammars
        have feot_u : (@g₁g_concat T g₁ g₂).FromEmbeddingString
            [Symbol.nonterminal (some (Sum.inl g₁.initial))] := by
          intro a ha
          simp only [List.mem_cons, List.not_mem_nil, or_false] at ha
          rw [ha]
          exact ⟨Symbol.nonterminal g₁.initial, by simp [g₁g_concat, Symbol.map]⟩
        have feot_v : (@g₂g_concat T g₁ g₂).FromEmbeddingString
            [Symbol.nonterminal (some (Sum.inr g₂.initial))] := by
          intro a ha
          simp only [List.mem_cons, List.not_mem_nil, or_false] at ha
          rw [ha]
          exact ⟨Symbol.nonterminal g₂.initial, by simp [g₂g_concat, Symbol.map]⟩
        have hu_filter := (@g₁g_concat T g₁ g₂).derives_filterMap hu'' feot_u
          (by
            intro t
            exact ⟨t, by simp [g₁g_concat, Symbol.map]⟩)
        have hv_filter := (@g₂g_concat T g₁ g₂).derives_filterMap hv'' feot_v
          (by
            intro t
            exact ⟨t, by simp [g₂g_concat, Symbol.map]⟩)
        -- Extract the terminal words
        set w₁ := extractTerminals u''
        set w₂ := extractTerminals v''
        -- Show that u'' and v'' consist only of terminals
        have u_terminals : ∀ x ∈ u'', ∃ t : T, x = Symbol.terminal t := by
          intro x hx
          have : x ∈ u'' ++ v'' := List.mem_append_left v'' hx
          rw [huv''] at this
          simp only [List.mem_map] at this
          obtain ⟨t, _, rfl⟩ := this
          exact ⟨t, rfl⟩
        have v_terminals : ∀ x ∈ v'', ∃ t : T, x = Symbol.terminal t := by
          intro x hx
          have : x ∈ u'' ++ v'' := List.mem_append_right u'' hx
          rw [huv''] at this
          simp only [List.mem_map] at this
          obtain ⟨t, _, rfl⟩ := this
          exact ⟨t, rfl⟩
        -- Show these are in the languages
        use w₁, ?_, w₂, ?_, ?_
        · -- w₁ ∈ g₁.language
          have eq1 : w₁.map Symbol.terminal =
            u''.filterMap g₁g_concat.project := by
            have : w₁ =
              extractTerminals (u''.filterMap g₁g_concat.project) := by
              rw [(extractTerminals_filterMap_terminals g₁g_concat.project
                (by intro t; simp [g₁g_concat]) u'' u_terminals).symm]
            rw [this]
            exact map_terminal_extractTerminals _ (
              filterMap_only_terminals _ (by intro t; simp [g₁g_concat]) _ u_terminals
            )
          simp only [mem_language_iff, eq1]
          simpa [g₁g_concat] using hu_filter
        · -- w₂ ∈ g₂.language
          have eq2 : w₂.map Symbol.terminal =
            v''.filterMap g₂g_concat.project := by
            have : w₂ =
              extractTerminals (v''.filterMap g₂g_concat.project) := by
              rw [(extractTerminals_filterMap_terminals g₂g_concat.project
                (by intro t; simp [g₂g_concat]) v'' v_terminals).symm]
            rw [this]
            exact map_terminal_extractTerminals _ (
              filterMap_only_terminals _ (by intro t; simp [g₂g_concat]) _ v_terminals
            )
          simp only [mem_language_iff, eq2]
          simpa [g₂g_concat] using hv_filter
        · -- w = w₁ ++ w₂
          calc w = extractTerminals (w.map (Symbol.terminal (N := (g₁.concat g₂).NT))) :=
                (extractTerminals_map_terminal (N := (g₁.concat g₂).NT) w).symm
            _ = extractTerminals (u'' ++ v'') := by rw [huv'']
            _ = extractTerminals u'' ++ extractTerminals v'' := extractTerminals_append _ _
            _ = w₁ ++ w₂ := rfl
      · exfalso
        -- Show this case is impossible: none can't appear in the mapped rules
        letI : DecidableEq T := Classical.decEq T
        letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
        letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
        letI : DecidableEq (Option (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
        letI : DecidableEq (ContextFreeRule T (Option (g₁.NT ⊕ g₂.NT))) := Classical.decEq _
        rw [Finset.mem_union] at hr
        cases hr with
        | inl hr =>
          rw [Finset.mem_map] at hr
          obtain ⟨r₀, _, hr_eq⟩ := hr
          simp only [ContextFreeRule.map] at huv hr_eq
          rw [← hr_eq] at huv
          simp at huv
        | inr hr =>
          rw [Finset.mem_map] at hr
          obtain ⟨r₀, _, hr_eq⟩ := hr
          simp only [ContextFreeRule.map] at huv hr_eq
          rw [← hr_eq] at huv
          simp at huv
  · rintro ⟨w₁, hw₁, w₂, hw₂, rfl⟩
    exact in_concat_of_in_left_and_right hw₁ hw₂

end concat_aux

/-- The class of context-free languages is closed under concatenation. -/
theorem Language.IsContextFree.mul {L₁ L₂ : Language T} :
    L₁.IsContextFree → L₂.IsContextFree → (L₁ * L₂).IsContextFree := by
  rintro ⟨g₁, rfl⟩ ⟨g₂, rfl⟩
  refine ⟨g₁.concat g₂, ?_⟩
  ext w
  rw [Language.mem_mul, ContextFreeGrammar.mem_concat_language_iff_mem_mul]
  constructor
  · intro ⟨w₁, hw₁, w₂, hw₂, heq⟩
    exact ⟨w₁, hw₁, w₂, hw₂, heq.symm⟩
  · intro ⟨w₁, hw₁, w₂, hw₂, heq⟩
    exact ⟨w₁, hw₁, w₂, hw₂, heq.symm⟩

end closure_concatenation

section substitution

namespace ContextFreeGrammar

/-- Map symbols of the original grammar, replacing terminal `t` by the start symbol of `g₂`. -/
def substSymbol (t : T) (g₁ g₂ : ContextFreeGrammar T) [DecidableEq T] :
    Symbol T g₁.NT → Symbol T (g₁.NT ⊕ g₂.NT)
  | .terminal a => if a = t then .nonterminal (Sum.inr g₂.initial) else .terminal a
  | .nonterminal n => .nonterminal (Sum.inl n)

lemma substSymbol_injective (t : T) (g₁ g₂ : ContextFreeGrammar T) [DecidableEq T] :
    (substSymbol t g₁ g₂).Injective := by
  intro s₁ s₂ h
  cases s₁ with
  | terminal a =>
      cases s₂ with
      | terminal b =>
          by_cases ha : a = t <;> by_cases hb : b = t
          · simp [substSymbol, ha, hb] at h; simp [ha, hb]
          · simp [substSymbol, ha, hb] at h
          · simp [substSymbol, ha, hb] at h
          · simp [substSymbol, ha, hb] at h; simp [h]
      | nonterminal b =>
          by_cases ha : a = t
          · simp [substSymbol, ha] at h
          · simp [substSymbol, ha] at h
  | nonterminal a =>
      cases s₂ with
      | terminal b =>
          by_cases hb : b = t
          · simp [substSymbol, hb] at h
          · simp [substSymbol, hb] at h
      | nonterminal b =>
          simpa [substSymbol] using h

/-- Grammar obtained by substituting terminal `t` in `g₁` with the start symbol of `g₂`. -/
noncomputable def substsgrammar (t : T) (g₁ g₂ : ContextFreeGrammar T) :
    ContextFreeGrammar T where
  NT := g₁.NT ⊕ g₂.NT
  initial := Sum.inl g₁.initial
  rules := by
    letI : DecidableEq T := Classical.decEq T
    let f₁ : ContextFreeRule T g₁.NT → ContextFreeRule T (g₁.NT ⊕ g₂.NT) :=
      fun r => ⟨Sum.inl r.input, r.output.map (substSymbol t g₁ g₂)⟩
    let f₂ : ContextFreeRule T g₂.NT → ContextFreeRule T (g₁.NT ⊕ g₂.NT) :=
      fun r => r.map Sum.inr
    have h₁ : f₁.Injective := by
      intro r₁ r₂ h
      cases r₁ with
      | mk r₁_in r₁_out =>
        cases r₂ with
        | mk r₂_in r₂_out =>
          simp only [ContextFreeRule.mk.injEq, Sum.inl.injEq, f₁] at h
          obtain ⟨hin, hout⟩ := h
          apply ContextFreeRule.ext
          · simpa using hin
          · exact (List.map_inj_right (substSymbol_injective t g₁ g₂)).1 hout
    have h₂ : f₂.Injective := by
      intro r₁ r₂ h
      simp only [ContextFreeRule.map, ContextFreeRule.mk.injEq, Sum.inr.injEq, f₂] at h
      obtain ⟨hin, hout⟩ := h
      apply ContextFreeRule.ext
      · simpa using hin
      · have :
            (Symbol.map (T := T) (N₀ := g₂.NT) (N := g₁.NT ⊕ g₂.NT) Sum.inr).Injective := by
          intro s1 s2 hs
          cases s1 <;> cases s2 <;> simp only [Symbol.map, Symbol.terminal.injEq] at hs ⊢
          repeat' grind
        exact (List.map_inj_right this).mp hout
    let mapped1 : Finset (ContextFreeRule T (g₁.NT ⊕ g₂.NT)) := g₁.rules.map ⟨f₁, h₁⟩
    let mapped2 : Finset (ContextFreeRule T (g₁.NT ⊕ g₂.NT)) := g₂.rules.map ⟨f₂, h₂⟩
    letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
    letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
    letI : DecidableEq (g₁.NT ⊕ g₂.NT) := Classical.decEq _
    letI : DecidableEq (ContextFreeRule T (g₁.NT ⊕ g₂.NT)) := Classical.decEq _
    exact mapped1 ∪ mapped2

noncomputable def substg₁_project (t : T) (g₁ g₂ : ContextFreeGrammar T) [DecidableEq T] :
    Symbol T (g₁.NT ⊕ g₂.NT) → Option (Symbol T g₁.NT) := by
  classical
  intro s
  cases s with
  | terminal a => exact some (.terminal a)
  | nonterminal n =>
      cases n with
      | inl n => exact some (.nonterminal n)
      | inr n => exact if n = g₂.initial then some (.terminal t) else none

@[simp] lemma substg₁_project_terminal (t : T) (g₁ g₂ : ContextFreeGrammar T) [DecidableEq T]
    (a : T) :
    substg₁_project t g₁ g₂ (.terminal a) = some (.terminal a) := by
  classical
  rfl

@[simp] lemma substg₁_project_nonterminal_inl (t : T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] (n : g₁.NT) :
    substg₁_project t g₁ g₂ (.nonterminal (Sum.inl n)) = some (.nonterminal n) := by
  classical
  rfl

@[simp] lemma substg₁_project_nonterminal_inr (t : T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] [DecidableEq g₂.NT] (n : g₂.NT) :
    substg₁_project t g₁ g₂ (.nonterminal (Sum.inr n)) =
      (if n = g₂.initial then some (Symbol.terminal t) else none) := by
  classical
  simp [substg₁_project]

noncomputable def substg₁_embedding (t : T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] :
    ContextFreeGrammar.Embedding g₁ (substsgrammar t g₁ g₂) where
  embed := by
    classical
    exact @substSymbol T t g₁ g₂ (Classical.decEq T)
  project := substg₁_project t g₁ g₂
  project_embed := by
    classical
    letI : DecidableEq T := Classical.decEq T
    letI : DecidableEq g₂.NT := Classical.decEq _
    intro s
    cases s with
    | terminal a =>
        by_cases h : a = t
        · have : substSymbol t g₁ g₂ (.terminal a) =
              Symbol.nonterminal (Sum.inr g₂.initial) := by
            simp [substSymbol, h]
          simp only [this, substg₁_project_nonterminal_inr, ↓reduceIte, Option.some.injEq,
            Symbol.terminal.injEq]
          exact h.symm
        · have : substSymbol t g₁ g₂ (.terminal a) = Symbol.terminal a := by
            simp [substSymbol, h]
          simp [this]
    | nonterminal n =>
        simp [substSymbol, substg₁_project]
  embed_nonterminal := by
    intro n₀
    exact ⟨Sum.inl n₀, rfl⟩
  embed_mem_rules := by
    intro r hr n h
    classical
    letI : DecidableEq T := Classical.decEq T
    have hn : n = Sum.inl r.input := by
      simpa [substSymbol] using (Symbol.nonterminal.inj h.symm)
    subst hn
    simp only [substsgrammar, Lean.Elab.WF.paramLet, Finset.mem_union, Finset.mem_map,
      Embedding.coeFn_mk]
    left
    exact ⟨r, hr, rfl⟩
  preimage_of_rules := by
    intro r hr n₀ heq
    classical
    letI : DecidableEq T := Classical.decEq T
    have hinput : r.input = Sum.inl n₀ := by
      simpa [substSymbol] using (Symbol.nonterminal.inj heq).symm
    simp only [substsgrammar, Lean.Elab.WF.paramLet, Finset.mem_union, Finset.mem_map,
      Embedding.coeFn_mk] at hr
    rcases hr with hr | hr
    · rcases hr with ⟨r₀, hr₀, hr_eq⟩
      have hr_input : r.input = Sum.inl r₀.input := by
        simpa [ContextFreeRule.mapSymbol] using (congrArg ContextFreeRule.input hr_eq).symm
      have hinput' : r₀.input = n₀ := by
        have : (Sum.inl n₀ : g₁.NT ⊕ g₂.NT) = Sum.inl r₀.input := by
          simp [hinput, hr_input.symm]
        exact Sum.inl_injective this.symm
      refine ⟨r₀, hr₀, hinput', ?_⟩
      have : ContextFreeRule.mapSymbol (T := T) r₀ (substSymbol t g₁ g₂) (Sum.inl r₀.input) = r :=
        by
          simpa [ContextFreeRule.mapSymbol] using hr_eq
      simpa [hinput', hr_input] using this
    · rcases hr with ⟨r₀, hr₀, hr_eq⟩
      have hr_input : r.input = Sum.inr r₀.input := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have : Sum.inl n₀ = Sum.inr r₀.input := by
        simpa [hinput] using hr_input.symm
      cases this

noncomputable def substg₂_embedding (t : T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] :
    ContextFreeGrammar.Embedding g₂ (substsgrammar t g₁ g₂) where
  embed := Symbol.map Sum.inr
  project
    | .terminal a => some (.terminal a)
    | .nonterminal (Sum.inl _) => none
    | .nonterminal (Sum.inr n) => some (.nonterminal n)
  project_embed := by
    intro s
    cases s <;> rfl
  embed_nonterminal := by
    intro n₀
    exact ⟨Sum.inr n₀, rfl⟩
  embed_mem_rules := by
    intro r hr n h
    classical
    have hn : n = Sum.inr r.input := by
      simpa [Symbol.map] using (Symbol.nonterminal.inj h.symm)
    subst hn
    simp only [substsgrammar, Lean.Elab.WF.paramLet, Finset.mem_union, Finset.mem_map,
      Embedding.coeFn_mk]
    right
    exact ⟨r, hr, rfl⟩
  preimage_of_rules := by
    intro r hr n₀ heq
    classical
    have hinput : r.input = Sum.inr n₀ := by
      simpa [Symbol.map] using (Symbol.nonterminal.inj heq).symm
    simp only [substsgrammar, Lean.Elab.WF.paramLet, Finset.mem_union, Finset.mem_map,
      Embedding.coeFn_mk] at hr
    rcases hr with hr | hr
    · rcases hr with ⟨r₀, hr₀, hr_eq⟩
      have hr_input : r.input = Sum.inl r₀.input := by
        simpa [ContextFreeRule.mapSymbol] using (congrArg ContextFreeRule.input hr_eq).symm
      have : Sum.inr n₀ = Sum.inl r₀.input := by
        simpa [hinput] using hr_input.symm
      cases this
    · rcases hr with ⟨r₀, hr₀, hr_eq⟩
      have hr_input : r.input = Sum.inr r₀.input := by
        simpa [ContextFreeRule.map] using (congrArg ContextFreeRule.input hr_eq).symm
      have hinput' : r₀.input = n₀ := by
        have : (Sum.inr r₀.input : g₁.NT ⊕ g₂.NT) = Sum.inr n₀ := by
          simp [hinput, hr_input.symm]
        exact Sum.inr_injective this
      refine ⟨r₀, hr₀, hinput', ?_⟩
      have : ContextFreeRule.mapSymbol (T := T) r₀ (Symbol.map Sum.inr) (Sum.inr r₀.input) = r :=
        by simpa [ContextFreeRule.map, ContextFreeRule.mapSymbol, Symbol.map] using hr_eq
      simpa [hinput', hr_input] using this

private lemma derives_substword (t : T) (g₁ g₂ : ContextFreeGrammar T) [DecidableEq T] :
    ∀ (w' w : List T),
      w ∈ substword t g₂.language w' →
      (substsgrammar t g₁ g₂).Derives
        (w'.map (fun a => substSymbol t g₁ g₂ (.terminal a)))
        (w.map Symbol.terminal) := by
  intro w' w hw
  induction w' generalizing w with
  | nil =>
      have hw' : w ∈ (1 : Language T) := by
        simpa [substword] using hw
      have : w = [] := by
        simpa [Language.mem_one] using hw'
      subst this
      exact ContextFreeGrammar.Derives.refl _
  | cons a tail ih =>
      have hw' : w ∈ subst t g₂.language a * substword t g₂.language tail := by
        simpa [substword_head] using hw
      rcases (Language.mem_mul.mp hw') with ⟨w₁, hw₁, w₂, hw₂, hconcat⟩
      subst hconcat
      by_cases h : a = t
      · have hw₁' : w₁ ∈ g₂.language := by
          simpa [subst, h] using hw₁
        have w₁_derives : (substsgrammar t g₁ g₂).Derives
            [Symbol.nonterminal (Sum.inr g₂.initial)] (w₁.map Symbol.terminal) := by
          have hder : g₂.Derives [Symbol.nonterminal g₂.initial] (w₁.map Symbol.terminal) := by
            simpa [ContextFreeGrammar.mem_language_iff] using hw₁'
          simpa [substg₂_embedding, Symbol.map] using
            (ContextFreeGrammar.Embedding.derives_map
              (G := substg₂_embedding t g₁ g₂) hder)
        have tail_derives :
            (substsgrammar t g₁ g₂).Derives
              (tail.map (fun a => substSymbol t g₁ g₂ (.terminal a)))
              (w₂.map Symbol.terminal) := ih w₂ hw₂
        have hhead : substSymbol t g₁ g₂ (.terminal a) =
            Symbol.nonterminal (Sum.inr g₂.initial) := by
          simp [substSymbol, h]
        have head_derives :
            (substsgrammar t g₁ g₂).Derives
              ([substSymbol t g₁ g₂ (.terminal a)] ++
                tail.map (fun a => substSymbol t g₁ g₂ (.terminal a)))
              (w₁.map Symbol.terminal ++
                tail.map (fun a => substSymbol t g₁ g₂ (.terminal a))) := by
          simpa [hhead] using
            (ContextFreeGrammar.Derives.append_right (g := substsgrammar t g₁ g₂)
              w₁_derives (tail.map (fun a => substSymbol t g₁ g₂ (.terminal a))))
        have tail_derives' :
            (substsgrammar t g₁ g₂).Derives
              (w₁.map Symbol.terminal ++
                tail.map (fun a => substSymbol t g₁ g₂ (.terminal a)))
              (w₁.map Symbol.terminal ++ w₂.map Symbol.terminal) := by
          simpa using
            (ContextFreeGrammar.Derives.append_left (g := substsgrammar t g₁ g₂)
              tail_derives (w₁.map Symbol.terminal))
        simpa [List.map_append] using head_derives.trans tail_derives'
      · have hw₁' : w₁ = [a] := by
          simpa [subst, h] using hw₁
        subst hw₁'
        have tail_derives :
            (substsgrammar t g₁ g₂).Derives
              (tail.map (fun a => substSymbol t g₁ g₂ (.terminal a)))
              (w₂.map Symbol.terminal) := ih w₂ hw₂
        have hhead : substSymbol t g₁ g₂ (.terminal a) = Symbol.terminal a := by
          simp [substSymbol, h]
        have : (substsgrammar t g₁ g₂).Derives
            ([Symbol.terminal a] ++
              tail.map (fun a => substSymbol t g₁ g₂ (.terminal a)))
            ([Symbol.terminal a] ++ w₂.map Symbol.terminal) := by
          simpa using
            (ContextFreeGrammar.Derives.append_left (g := substsgrammar t g₁ g₂)
              tail_derives [Symbol.terminal a])
        simpa [hhead] using this

private lemma derives_terminal_eq {g : ContextFreeGrammar T} {s t : List (Symbol T g.NT)}
    (h : g.Derives s t) (hs : ∀ x ∈ s, ∃ a : T, x = Symbol.terminal a) :
    s = t := by
  -- If s consists only of terminals, no rule can apply, so derivation is trivial
  induction h with
  | refl => rfl
  | tail _ hprod ih =>
    -- If we have s →* u → t, then first show s = u
    have : s = _ := ih
    subst this
    -- Now show that no production can apply to an all-terminal string
    rcases hprod with ⟨r, hr_mem, hr_rew⟩
    -- A rule requires a nonterminal to match, but s has only terminals
    have := hr_rew.nonterminal_input_mem
    rcases hs _ this with ⟨a, ha⟩
    cases ha


private lemma all_symbols_are_terminals_implies_is_map_terminal {N : Type*} (s : List (Symbol T N)) :
    (∀ x ∈ s, ∃ t : T, x = Symbol.terminal t) ↔ ∃ w : List T, s = w.map Symbol.terminal := by
  constructor
  · intro hs
    induction s with
    | nil => exact ⟨[], rfl⟩
    | cons head tail ih =>
      have h_head := hs head (by simp)
      rcases h_head with ⟨t_head, rfl⟩
      have h_tail : ∀ x ∈ tail, ∃ t : T, x = Symbol.terminal t := fun x hx => hs x (by simp [hx])
      rcases ih h_tail with ⟨w_tail, rfl⟩
      exact ⟨t_head :: w_tail, by simp⟩
  · intro hw
    rcases hw with ⟨w, rfl⟩
    intro x hx
    simp only [List.mem_map] at hx
    rcases hx with ⟨t_in_w, _, h_eq_x⟩
    exact ⟨t_in_w, h_eq_x.symm⟩

-- Helper: g₁ nonterminal in substsgrammar derives to terminals
private lemma substg₁_nonterminal_derives (t : T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] {n : g₁.NT} {w : List T}
    (h : (substsgrammar t g₁ g₂).Derives
      [Symbol.nonterminal (Sum.inl n)] (w.map Symbol.terminal)) :
    ∃ w', g₁.Derives [Symbol.nonterminal n] (w'.map Symbol.terminal) ∧
      w ∈ substword t g₂.language w' := by
  sorry

-- Key lemma: any nonterminal Sum.inr n in substsgrammar (if it derives to terminals)
-- must be g₂.initial and derives a word in g₂.language
private lemma substg₂_derives_in_language (t : T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] {n : g₂.NT} {w : List T}
    (h : (substsgrammar t g₁ g₂).Derives
      [Symbol.nonterminal (Sum.inr n)] (w.map Symbol.terminal)) :
    n = g₂.initial ∧ w ∈ g₂.language := by
  sorry

-- General principle: derivation from nonterminal-based string to terminals
-- The filterMap gives a string that CAN DERIVE w' in g₁
private lemma derives_from_subst_symbols (t : T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] :
    ∀ (s : List (Symbol T (g₁.NT ⊕ g₂.NT))) (w : List T),
    (substsgrammar t g₁ g₂).Derives s (w.map Symbol.terminal) →
    (∀ x ∈ s, match x with
      | Symbol.terminal a => a ≠ t
      | Symbol.nonterminal (Sum.inl _) => True
      | Symbol.nonterminal (Sum.inr n) => n = g₂.initial) →
    ∃ w', g₁.Derives (s.filterMap (substg₁_project t g₁ g₂)) (w'.map Symbol.terminal) ∧
      w ∈ substword t g₂.language w' := by
  intro s w hder hs
  classical
  letI : DecidableEq T := Classical.decEq T
  letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
  letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
  induction s generalizing w with
  | nil =>
    have : w = [] := by
      have : ([] : List (Symbol T (g₁.NT ⊕ g₂.NT))) = w.map Symbol.terminal :=
        derives_terminal_eq hder (by simp)
      simp at this; exact this
    subst this
    use []
    simp [substword, Language.one_def, ContextFreeGrammar.Derives.refl]
    rfl
  | cons head tail ih =>
    -- Use head_tail_split to separate derivation
    obtain ⟨u, v, hu, hv, huv⟩ :=
      head_tail_split (g := substsgrammar t g₁ g₂) (w.map Symbol.terminal) head tail hder
    -- Extract terminal words from u and v
    -- This relies on `u` and `v` being lists of terminals because `u ++ v` is a list of terminals.
    have hu_terminals : ∀ x ∈ u, ∃ t_val : T, x = Symbol.terminal t_val := by
      intro x hx
      have : x ∈ u ++ v := List.mem_append_of_mem_left u v hx
      rw [huv] at this
      simp only [List.mem_map] at this
      rcases this with ⟨t_val, _, rfl⟩
      exact ⟨t_val, rfl⟩
    have hv_terminals : ∀ x ∈ v, ∃ t_val : T, x = Symbol.terminal t_val := by
      intro x hx
      have : x ∈ u ++ v := List.mem_append_of_mem_right u v hx
      rw [huv] at this
      simp only [List.mem_map] at this
      rcases this with ⟨t_val, _, rfl⟩
      exact ⟨t_val, rfl⟩
    -- Now use the new lemma to obtain u_term and v_term
    obtain ⟨u_term, hu_eq⟩ := (all_symbols_are_terminals_implies_is_map_terminal u).mp hu_terminals
    obtain ⟨v_term, hv_eq⟩ := (all_symbols_are_terminals_implies_is_map_terminal v).mp hv_terminals
    have w_eq : u_term ++ v_term = w := by
      -- huv is (u ++ v = w.map Symbol.terminal)
      -- After rw [hu_eq, hv_eq] at huv, huv is ((u_term.map Symbol.terminal) ++ (v_term.map Symbol.terminal) = w.map Symbol.terminal)
      rw [hu_eq, hv_eq] at huv
      -- simp only [List.map_append] at huv
      -- huv is now (u_term ++ v_term).map Symbol.terminal = w.map Symbol.terminal
      have hinj : Function.Injective (β:=Symbol T g₁.NT) Symbol.terminal := by
        intro a b h; cases h; rfl
      exact (List.map_injective_iff _).2 hinj huv
    subst w_eq
    -- Apply IH to tail
    have hs_tail : ∀ x ∈ tail, match x with
        | Symbol.terminal a => a ≠ t
        | Symbol.nonterminal (Sum.inl _) => True
        | Symbol.nonterminal (Sum.inr n) => n = g₂.initial := by
      intro x hx
      apply hs
      simp [hx]
    rcases ih v_term (hv_eq ▸ hv) hs_tail with ⟨w'_tail, hw'_tail_derives, hw'_tail_in⟩
    -- Handle head by cases
    cases head with
    | terminal a =>
      -- Terminal a (must have a ≠ t by assumption)
      have ha_ne : a ≠ t := hs _ (by
        simp_all only [ne_eq, implies_true, forall_const, List.mem_map, forall_exists_index, and_imp,
          forall_apply_eq_imp_iff₂, Symbol.terminal.injEq, exists_eq', List.map_append, List.mem_cons, or_true,
          forall_eq_or_imp]
        apply Or.inl
        rfl -- aesop generated
      )
      -- Derives only itself
      have : u_term = [a] := by
        have h_u_term_eq_a : [Symbol.terminal a] = u_term.map Symbol.terminal := by
          rw [hu_eq]
          apply derives_terminal_eq (g := substsgrammar t g₁ g₂) hu
          intro x hx
          simp at hx
          subst hx
          exact ⟨a, rfl⟩
        have hinj : Function.Injective Symbol.terminal := by intro _ _ h; cases h; rfl
        exact (List.map_injective_iff _).2 hinj h_u_term_eq_a
      subst this
      use [a] ++ w'_tail
      constructor
      · simp [List.filterMap, substg₁_project]
        exact ContextFreeGrammar.Derives.append_right hw'_tail_derives [Symbol.terminal a]
      · rw [substword_head]
        apply Language.mem_mul.mpr
        use [a], [a]
        simp [subst, ha_ne]
        exact ⟨rfl, w'_tail, hw'_tail_in, rfl⟩
    | nonterminal n =>
      cases n with
      | inl n₁ =>
        -- g₁ nonterminal - use the helper lemma
        rcases substg₁_nonterminal_derives t g₁ g₂ (hu_eq ▸ hu) with ⟨w'_head, hw'_head_derives, hw'_head_in⟩
        use w'_head ++ w'_tail
        constructor
        · simp [List.filterMap, substg₁_project]
          rw [←List.map_append]
          exact (hw'_head_derives.append_right (List.filterMap (substg₁_project t g₁ g₂) tail)).trans
            (hw'_tail_derives.append_left (List.map Symbol.terminal w'_head))
        · rw [substword_append]
          apply Language.mem_mul.mpr
          exact ⟨_, hw'_head_in, _, hw'_tail_in, rfl⟩
      | inr n₂ =>
        -- g₂ nonterminal (must be g₂.initial)
        have hn₂ : n₂ = g₂.initial := hs _ (by simp)
        subst hn₂
        -- Derives a word in g₂.language using substg₂_embedding
        have : u_term ∈ g₂.language := by
          -- Use substg₂_embedding to show this
          have h_embed : (substg₂_embedding t g₁ g₂).FromEmbeddingString
              [Symbol.nonterminal (Sum.inr g₂.initial)] := by
            intro a ha
            simp at ha
            subst ha
            exact ⟨Symbol.nonterminal g₂.initial, by simp [substg₂_embedding]⟩
          have h_term : ∀ t' : T, ∃ t'' : T,
              (substg₂_embedding t g₁ g₂).embed (.terminal t') = .terminal t'' := by
            intro t'
            exact ⟨t', by simp [substg₂_embedding]⟩
          have hder_proj := (substg₂_embedding t g₁ g₂).derives_filterMap (hu_eq ▸ hu) h_embed h_term
          simp [substg₂_embedding] at hder_proj
          have : [Symbol.nonterminal (Sum.inr g₂.initial)].filterMap (substg₂_embedding t g₁ g₂).project =
              [Symbol.nonterminal g₂.initial] := by
            simp [List.filterMap, substg₂_embedding]
          rw [this] at hder_proj
          have : (u_term.map Symbol.terminal).filterMap (substg₂_embedding t g₁ g₂).project =
              u_term.map Symbol.terminal := by
            induction u_term with
            | nil => rfl
            | cons a tail ih => simp [List.filterMap, substg₂_embedding, ih]
          rw [this] at hder_proj
          exact hder_proj
        use [t] ++ w'_tail
        constructor
        · simp [List.filterMap, substg₁_project]
          exact ContextFreeGrammar.Derives.append_right hw'_tail_derives [Symbol.terminal t]
        · rw [substword_head]
          apply Language.mem_mul.mpr
          use u_term, u_term
          simp [subst]
          exact ⟨this, w'_tail, hw'_tail_in, rfl⟩

private lemma derives_substword_of_derives_start (t : T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] {w : List T} :
    (substsgrammar t g₁ g₂).Derives
        [Symbol.nonterminal (Sum.inl g₁.initial)]
        (w.map Symbol.terminal) →
    ∃ w' ∈ g₁.language, w ∈ substword t g₂.language w' := by
  intro hder
  classical
  letI : DecidableEq T := Classical.decEq T
  letI : DecidableEq g₁.NT := Classical.decEq g₁.NT
  letI : DecidableEq g₂.NT := Classical.decEq g₂.NT
  -- The general lemma applies
  have h_cond : ∀ x ∈ [Symbol.nonterminal (Sum.inl g₁.initial)], match x with
      | Symbol.terminal a => a ≠ t
      | Symbol.nonterminal (Sum.inl _) => True
      | Symbol.nonterminal (Sum.inr n) => n = g₂.initial := by
    intro x hx
    simp only [List.mem_singleton] at hx
    subst hx
    trivial
  rcases derives_from_subst_symbols t g₁ g₂ [Symbol.nonterminal (Sum.inl g₁.initial)] w hder h_cond with
    ⟨w', hw'_derives, hw_in⟩
  use w'
  constructor
  · -- Show w' ∈ g₁.language
    -- filterMap [Sum.inl g₁.initial] = [g₁.initial]
    have : [Symbol.nonterminal (Sum.inl g₁.initial)].filterMap (substg₁_project t g₁ g₂) =
        [Symbol.nonterminal g₁.initial] := by
      simp [List.filterMap, substg₁_project]
    rw [this] at hw'_derives
    exact hw'_derives
  · exact hw_in



theorem ContextFreeGrammar.subst_lang (t: T) (g₁ g₂ : ContextFreeGrammar T)
    [DecidableEq T] :
    (substsgrammar t g₁ g₂).language = (substlang t g₁.language g₂.language) := by
    refine Language.ext_iff.mpr ?_
    intro w
    constructor
    · intro w_in_substgrammar
      have hder :
          (substsgrammar t g₁ g₂).Derives
            [Symbol.nonterminal (Sum.inl g₁.initial)] (w.map Symbol.terminal) := by
        simpa [ContextFreeGrammar.mem_language_iff] using w_in_substgrammar
      rcases derives_substword_of_derives_start (t := t) (g₁ := g₁) (g₂ := g₂) hder with
        ⟨w', hw', hw⟩
      exact ⟨w', hw', hw⟩
    · intro w_in_sublang
      have w'_in_origlang: ∃w' ∈ g₁.language, w ∈ substword t g₂.language w' := by
        simp only [substlang, mem_language_iff] at w_in_sublang
        exact Set.inter_nonempty.mp w_in_sublang
      obtain ⟨w', w'_in_origlang⟩ := w'_in_origlang
      rcases w'_in_origlang with ⟨ha, hb⟩
      have w'_derives : g₁.Derives [Symbol.nonterminal g₁.initial] (w'.map Symbol.terminal) := by
        simpa [ContextFreeGrammar.mem_language_iff] using ha
      classical
      letI : DecidableEq T := Classical.decEq T
      have w'_derives_in_subst :
          (substsgrammar t g₁ g₂).Derives
            [Symbol.nonterminal (Sum.inl g₁.initial)]
            (w'.map (substSymbol t g₁ g₂ ∘ Symbol.terminal)) := by
        simpa [substg₁_embedding, Symbol.map, substSymbol, Function.comp] using
          (ContextFreeGrammar.Embedding.derives_map
            (G := substg₁_embedding t g₁ g₂) w'_derives)
      have w_derives_from_subst :
          (substsgrammar t g₁ g₂).Derives
            (w'.map (substSymbol t g₁ g₂ ∘ Symbol.terminal))
            (w.map Symbol.terminal) := by
        simpa [Function.comp] using derives_substword t g₁ g₂ w' w hb
      exact w'_derives_in_subst.trans w_derives_from_subst

end ContextFreeGrammar

end substitution
